bump_version: null
lint:
  base_config: false
  files_exist:
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - conf/igenomes.config
  - .editorconfig
  - .prettierignore
  - .prettierrc.yml
  - CITATIONS.md
  - assets/multiqc_config.yml
  - conf/base.config
  - conf/modules.config
  - modules.json
  - CHANGELOG.md
  - nextflow_schema.json
  - LICENSE
  - assets/email_template.html
  - assets/sendmail_template.txt
  - assets/email_template.txt
  - docs/output.md
  - docs/README.md
  - docs/usage.md
  - conf/test.config
  - conf/test_full.config
  - .github/workflows/ci.yml
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - .editorconfig
  - .prettierignore
  - .prettierrc.yml
  - CITATIONS.md
  - assets/multiqc_config.yml
  - conf/base.config
  - conf/modules.config
  - modules.json
  - CHANGELOG.md
  - nextflow_schema.json
  - LICENSE
  - assets/email_template.html
  - assets/sendmail_template.txt
  - assets/email_template.txt
  - docs/output.md
  - docs/README.md
  - docs/usage.md
  - conf/test.config
  - conf/test_full.config
  - .github/workflows/ci.yml
  - CODE_OF_CONDUCT.md
  - assets/nf-core-testmissingmain_logo_light.png
  - docs/images/nf-core-testmissingmain_logo_light.png
  - docs/images/nf-core-testmissingmain_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - .github/CONTRIBUTING.md
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - LICENSE
  - .prettierignore
  - .prettierignore
  - .prettierignore
  - .github/CONTRIBUTING.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/CONTRIBUTING.md
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - LICENSE
  - .prettierignore
  - .prettierignore
  - .prettierignore
  - .github/CONTRIBUTING.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - CODE_OF_CONDUCT.md
  - assets/nf-core-testmissingmain_logo_light.png
  - docs/images/nf-core-testmissingmain_logo_light.png
  - docs/images/nf-core-testmissingmain_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  included_configs: false
  modules_config: false
  modules_json: false
  multiqc_config: false
  nextflow_config: false
  nfcore_components: false
  readme:
  - nextflow_badge
  schema_description: false
  schema_lint: false
  schema_params: false
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: as
  description: as
  force: true
  is_nfcore: false
  name: testmissingmain
  org: FriederikeHanssen
  outdir: .
  skip_features:
  - ci
  - igenomes
  - github_badges
  - nf_core_configs
  - code_linters
  - citations
  - gitpod
  - codespaces
  - multiqc
  - fastqc
  - modules
  - changelog
  - nf_schema
  - license
  - email
  - adaptivecard
  - slackreport
  - documentation
  - test_config
  - seqera_platform
  version: 1.0.0dev
update: null
